[tool.poetry]
name = "pkm-buildsys"
version = "0.2.2"
description = "Fork of poetry-core, with some relaxations"
authors = [ "bennylut"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/bennylut/relaxed-poetry-core"
repository = "https://github.com/bennylut/relaxed-poetry-core"
keywords = [ "packaging",  "dependency",  "poetry",  "relaxed-poetry"]
classifiers = [ "Topic :: Software Development :: Build Tools",  "Topic :: Software Development :: Libraries :: Python Modules"]
exclude = [ "**/*.pyc",  "**/*.pyi"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/bennylut/relaxed-poetry/issues"

[tool.poetry.dependencies]
python = "^3.6"
importlib-metadata = {version = ">=1.7.0", python = "<3.8"}
dataclasses = {version = ">=0.8", python = "~3.6"}

[tool.vendoring]
destination = "poetry/core/_vendor/"
requirements = "poetry/core/_vendor/vendor.txt"
namespace = ""
protected-files = [ "__init__.py",  "README.md",  "vendor.txt"]
patches-dir = "vendors/patches"

[tool.vendoring.transformations]
substitute = []
drop = [ "bin/",  "*.so",  "typing.*",  "*/tests/"]

[tool.vendoring.typing-stubs]
six = [ "six.__init__",  "six.moves.__init__",  "six.moves.configparser"]
appdirs = []

[tool.vendoring.license.fallback-urls]
pyrsistent = "https://raw.githubusercontent.com/tobgu/pyrsistent/master/LICENSE.mit"

[build-system]
requires = [ "dataclasses>=0.6;python_version < '3.7'"]
build-backend = "poetry.core.masonry.api"
backend-path = [ "."]