# Generated by Django 2.2.24 on 2021-10-15 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inputflow', '0004_auto_20200225_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='input',
            name='related_model',
            field=models.ForeignKey(blank=True, default=None, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='input',
            name='related_model_object_id',
            field=models.PositiveIntegerField(blank=True, default=None, editable=False, null=True),
        ),
    ]
