
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-28T01:11:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cf3df5ac85ccec60790aa7f2ff54d9e303520fde",
 "version": "v0.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
