[tool.poetry]
name = "python_dataset"
version = "0.0.4"
description = ""
authors = ["kjun1 <p.k.maejima1211@icloud.com>"]

[tool.poetry.dependencies]
python = "^3.7.11"
pyworld = "^0.2.12"
pysptk = "^0.1.18"
opencv-python = "^4.5.2"
pandas = "^1.2.4"
librosa = "^0.8.1"
toml = "^0.10.2"
jupyterlab = "^3.1.4"
torch = "^1.10.0"
torchaudio = "^0.10.0"
soxr = "^0.2.6"

[tool.poetry.dev-dependencies]
black = "^21.7b0"
flake8 = "^3.9.2"
mypy = "^0.910"
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
