[dependencies]
serde_json = "1.0"

[dependencies.jsonschema-transpiler]
path = "local_dependencies/jsonschema-transpiler"

[dependencies.pyo3]
features = ["extension-module"]
version = "0.14.5"

[lib]
crate-type = ["cdylib"]
name = "jst"

[package]
authors = ["kitagawa-hr <kitagawahr@gmail.com>"]
description = "A tool to transpile JSON Schema into schemas for data processing"
edition = "2018"
license = "MPL-2.0"
name = "jsonschema-transpiler-py"
readme = "README.md"
repository = "https://github.com/kitagawa-hr/jsonschema-transpiler"
version = "1.10.0"
