[tool.poetry]
name = "bench-cli"
version = "0.1.6"
description = ""
authors = ["Malcolm Gillespie <malcolmgillespie@outlook.com>"]
readme = "README.md"
homepage = "https://github.com/mlcgp/bench"
repository = "https://github.com/mlcgp/bench-cli"
keywords = ["finance", "portfolio", "investing", "data-science", "data-visualization", "analytics", "dashboards", "metrics"]
packages = [
    {include="bench"},
]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
requests-futures = "^1.0.0"
pandas = "^1.3.3"
psycopg2 = "^2.9.1"
dash = "^2.0.0"
typer = "^0.4.0"
pyfiglet = "^0.8.post1"
python-dotenv = "^0.19.1"
schedule = "^1.1.0"
SQLAlchemy = "^1.4.26"
tabulate = "^0.8.9"
alive-progress = "^2.1.0"
inflection = "^0.5.1"
dash-bootstrap-components = "^1.0.0"
plotly-express = "^0.4.1"

[tool.poetry.dev-dependencies]

[tool.poetry.plugins."console_scripts"]
bench = "bench.cli:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
