# If any of these fields are missing in your config, then this config's
# fields replace them automatically

[CONFIG]
TIMEOUT = {"DEFAULT"=1} # Student's program is terminated if it takes more than this time in seconds
GENERATE_RESULTS = true # Generate results directory with a result file per student
TOTAL_POINTS_POSSIBLE = 100 # Total points given for tests
ASSIGNMENT_NAME = "Homework" # For display in the output for the student
POSSIBLE_SOURCE_FILE_STEMS = [] # At least one of these names must be in each submission's name. Empty means that we grade all submissions.
TESTCASE_WEIGHTS = {"DEFAULT"= 1} # A list of testcase_filename=maximum_result_percentage values.
STDOUT_ONLY_GRADING_ENABLED = false # Grade in stdout-only mode (Requires 'Possible Source File Stems')
PARALLEL_GRADING_ENABLED = true # Grade multiple submissions at once.
SUBMISSION_PRECOMPILATION_ARGS = {} # Extra arguments to be passed with each submission during pre-compilation
TESTCASE_PRECOMPILATION_ARGS = {} # Extra arguments to be passed with each testcase during pre-compilation
TESTCASE_COMPILATION_ARGS = {} # Extra arguments to be passed with each testcase during compilation
TESTCASE_RUNTIME_ARGS = {} # Extra arguments to be passed to each testcase during runtime

[GCC]
MEMORY_LEAK_DETECTION = false # if true, memory leak summary will be generated for each student submission