
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-29T15:12:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "eab229fc26f8b08a7b6dd3ea05cb5fa9758512bb",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
