
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-02T14:04:48+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "4e64bf49339c8e4060dade1ee0734eb1ff787a7e",
 "version": "2552"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
