
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-28T20:53:40+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8949b2c76fbf62c492b0e326e16db15abf7d6365",
 "version": "0.9.16"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
