[tool.poetry]
name = "strigiform"
version = "0.0.4"
description = "strigiform"
authors = ["Alex McKay <aldmckay@gmail.com>"]
license = "MIT"
readme = "README.rst"
homepage = "https://github.com/X-McKay/strigiform"
repository = "https://github.com/X-McKay/strigiform"
documentation = "https://strigiform.readthedocs.io"

classifiers = [
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[tool.poetry.urls]
Changelog = "https://github.com/X-McKay/strigiform/releases"

[tool.poetry.dependencies]
python = "^3.7.9"
click = "*"
requests = "2.26.0"
types-requests = "^2.25.0"
pandas = "^1.2.5"
pandas-stubs = "^1.2.0"
click-help-colors = "^0.9.1"
nox-poetry = "^0.8.6"
botocore = "^1.21.29"
importlib-metadata = "<4.9.0"
pytest-responsemock = {extras = ["dev"], version = "^1.0.1"}
psycopg2 = "^2.9.1"
configparser = "^5.0.2"
sql = "^0.4.0"
SQLAlchemy = "1.4.23"
mock = "^4.0.3"
streamlit = "^1.0.0"
requests-mock = "*"
hvac = "^0.11.2"
parameterized = "^0.8.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
coverage = {extras = ["toml"], version = "^5.5"}
safety = "^1.10.3"
mypy = "^0.910"
typeguard = "^2.12.1"
xdoctest = {extras = ["colors"], version = "^0.15.8"}
sphinx = "^4.0.2"
sphinx-autobuild = "^2021.3.14"
pre-commit = "<2.15.1"
flake8 = "^3.9.2"
black = "^21.9b0"
flake8-bandit = "^2.1.2"
flake8-bugbear = "^21.4.3"
flake8-docstrings = "^1.6.0"
flake8-rst-docstrings = "^0.2.3"
pep8-naming = "^0.12.1"
darglint = "^1.8.0"
reorder-python-imports = "^2.5.0"
pre-commit-hooks = "^4.0.1"
sphinx-rtd-theme = "^1.0.0"
sphinx-click = "^3.0.1"
Pygments = "^2.9.0"
pytest-cov = "^2.12.1"

[tool.poetry.scripts]
strigiform = "strigiform.core.cli:main"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["strigiform"]

[tool.coverage.report]
show_missing = true
fail_under = 60

[tool.mypy]
strict = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
