[tool.poetry]
name = "splitn"
version = "2.0.2"
description = ""
authors = ["Michał Warzocha <warzocha.michal@icloud.com>"]
readme = "README.md"

[tool.poetry.scripts]
splitn = "splitn.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.3.2"}
rstr = "^3.0.0"
loguru = "^0.5.3"
split = "split:main"
sequences = "sequences:main"

[tool.poetry.dev-dependencies]
flake8 = "^3.9.0"
pytest = "^4.6"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
