[tool.poetry]
name = "hellobiswatest"
version = "0.1.88"
description = "a pypi package for testing purposes by biswaroop1547"
authors = ["Biswaroop Bhattacharjee <biswaroop08@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
pytest = "^6.2.5"
black = "^21.9b0"
mypy = "^0.910"
pytest-cov = "^3.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
