#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['muzzle']

package_data = \
{'': ['*']}

install_requires = \
['defusedxml', 'xmltodict']

extras_require = \
{'dev': ['flit'], 'test': ['flake8', 'mock', 'pytest', 'pytest-cov']}

setup(name='muzzle',
      version='0.0.1',
      description='A tiny xmlparser',
      author=None,
      author_email='Stefan Oderbolz <odi@metaodi.ch>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.7',
     )
