[tool.poetry]
name = "pkm-installer"
version = "0.2.1"
description = "lightweight installer for pkm"
authors = [ "bennyl"]
license = "MIT License"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"
importlib-metadata = {version = ">=1.7.0", python = "<3.8"}

[build-system]
requires = [ "relaxed-poetry-core>=0.3.0"]
build-backend = "poetry.core.masonry.api"