
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-31T12:12:38-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "b203e4603bb7f83362862c4f94711cc7f6ac148d",
 "version": "5.1.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
