[tool.poetry]
name = "sp110e"
version = "0.1.0"
description = "Control SP110E BLE RGB LED device from computer"
authors = ["Pavel Roslovets <p.v.roslovets@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
bleak = "==0.13.0"
syncer = "==1.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
