
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-01T11:48:10+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f5a475330f4359333c6ab37a2559dbf931910fb",
 "version": "0.7.1.post.dev132"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
