# Generated by Django 3.2 on 2021-10-27 05:32

from django.db import migrations, models
import django.db.models.deletion
import django_rest_admin.model_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteExec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.TextField(blank=True, null=True)),
                ('table_name', models.TextField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, help_text='表功能描述', null=True)),
                ('foreign_key_id', django_rest_admin.model_field.JSONField(blank=True, help_text='外键定义.关联删除属性：CASCADE-关联删除, SET_NULL-字段变空, DO_NOTHING-不做操作', null=True)),
                ('foreign_key_ro', django_rest_admin.model_field.JSONField(blank=True, help_text='外键关联的只读内容', null=True)),
                ('foreign_slug_kf', django_rest_admin.model_field.JSONField(blank=True, help_text='一对多外键关联的字段列表', null=True)),
                ('ordering_fields', django_rest_admin.model_field.JSONField(blank=True, help_text='可用排序字段，数组，每个项是字符串', null=True)),
                ('ordering', django_rest_admin.model_field.JSONField(blank=True, help_text='默认排序字段，数组，每个项是字符串', null=True)),
                ('no_need_login', models.IntegerField(blank=True, help_text='是否需要登陆。1，0', null=True)),
                ('search_fields', django_rest_admin.model_field.JSONField(blank=True, help_text='可用排序字段，数组，每个项是字符串', null=True)),
                ('filter_keys', django_rest_admin.model_field.JSONField(blank=True, help_text='过滤项', null=True)),
                ('model_object_list', django_rest_admin.model_field.JSONField(blank=True, help_text='可显示字段', null=True)),
                ('params', django_rest_admin.model_field.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'table-REST-CRUD',
                'db_table': 'rest_admin_table_crud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComputedField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_text', django_rest_admin.model_field.CodeField(blank=True, help_text='py函数.eg: def jine(self):return 0', null=True)),
                ('route_exec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_admin.routeexec')),
            ],
            options={
                'verbose_name_plural': '计算函数字段',
                'db_table': 'rest_admin_table_crud_computed_field',
                'managed': True,
            },
        ),
    ]
