site_name: Django Ninja Extra
site_description: Django Ninja Extra - Adds more power to Django Ninja RESTful api library
site_url: https://eadwincode.github.io/django-ninja-extra/
repo_name: eadwinCode/django-ninja
repo_url: https://github.com/eadwinCode/django-ninja-extra
edit_uri: ''

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deeppurple
      accent: deeppurple
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

  language: en
  icon:
    repo: fontawesome/brands/git-alt
nav:
- Intro: index.md
