# Generated by Django 3.2 on 2021-10-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_admin', '0002_auto_20211027_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routeexec',
            name='table_name',
        ),
        migrations.AddField(
            model_name='routeexec',
            name='table_big_name',
            field=models.TextField(blank=True, help_text='the model name of a table. eg: Danwei', null=True),
        ),
    ]
