# flake8: noqa

"""
    Nomad CBEC

    This is the API descriptor for the Nomad CBEC, responsible for CBEC customer ID check. Developed by `Samarkand Global <https://samarkand.global>`_  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.5.0"

# import ApiClient
from nomad_cbec_id_cli.api_client import ApiClient

# import Configuration
from nomad_cbec_id_cli.configuration import Configuration

# import exceptions
from nomad_cbec_id_cli.exceptions import OpenApiException
from nomad_cbec_id_cli.exceptions import ApiAttributeError
from nomad_cbec_id_cli.exceptions import ApiTypeError
from nomad_cbec_id_cli.exceptions import ApiValueError
from nomad_cbec_id_cli.exceptions import ApiKeyError
from nomad_cbec_id_cli.exceptions import ApiException
