# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/proxy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/proxy.proto',
  package='proxy',
  syntax='proto3',
  serialized_options=b'\252\002\017ProxyApiService',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11proto/proxy.proto\x12\x05proxy\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n\x0cProxyRequest\x12\r\n\x05\x63ount\x18\x01 \x01(\x05\x12\x0e\n\x06source\x18\x02 \x01(\t\"<\n\nProxyReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x1d\n\x07Proxies\x18\x02 \x03(\x0b\x32\x0c.proxy.Proxy\"\xf6\x01\n\x05Proxy\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x10\n\x08username\x18\x04 \x01(\t\x12\x10\n\x08password\x18\x05 \x01(\t\x12\x0e\n\x06status\x18\x06 \x01(\x08\x12\x31\n\rrelevant_from\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x32\n\x0erelevant_until\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0bstatus_egov\x18\t \x01(\x08\x12\x12\n\ncountry_id\x18\n \x01(\x05\x32@\n\x08ProxyApi\x12\x34\n\nGetProxies\x12\x13.proxy.ProxyRequest\x1a\x11.proxy.ProxyReplyB\x12\xaa\x02\x0fProxyApiServiceb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_PROXYREQUEST = _descriptor.Descriptor(
  name='ProxyRequest',
  full_name='proxy.ProxyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='count', full_name='proxy.ProxyRequest.count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='source', full_name='proxy.ProxyRequest.source', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=106,
)


_PROXYREPLY = _descriptor.Descriptor(
  name='ProxyReply',
  full_name='proxy.ProxyReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='proxy.ProxyReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Proxies', full_name='proxy.ProxyReply.Proxies', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=108,
  serialized_end=168,
)


_PROXY = _descriptor.Descriptor(
  name='Proxy',
  full_name='proxy.Proxy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proxy.Proxy.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='proxy.Proxy.address', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='port', full_name='proxy.Proxy.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='username', full_name='proxy.Proxy.username', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='password', full_name='proxy.Proxy.password', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='proxy.Proxy.status', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relevant_from', full_name='proxy.Proxy.relevant_from', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relevant_until', full_name='proxy.Proxy.relevant_until', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_egov', full_name='proxy.Proxy.status_egov', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='country_id', full_name='proxy.Proxy.country_id', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=417,
)

_PROXYREPLY.fields_by_name['Proxies'].message_type = _PROXY
_PROXY.fields_by_name['relevant_from'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_PROXY.fields_by_name['relevant_until'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['ProxyRequest'] = _PROXYREQUEST
DESCRIPTOR.message_types_by_name['ProxyReply'] = _PROXYREPLY
DESCRIPTOR.message_types_by_name['Proxy'] = _PROXY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProxyRequest = _reflection.GeneratedProtocolMessageType('ProxyRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROXYREQUEST,
  '__module__' : 'proto.proxy_pb2'
  # @@protoc_insertion_point(class_scope:proxy.ProxyRequest)
  })
_sym_db.RegisterMessage(ProxyRequest)

ProxyReply = _reflection.GeneratedProtocolMessageType('ProxyReply', (_message.Message,), {
  'DESCRIPTOR' : _PROXYREPLY,
  '__module__' : 'proto.proxy_pb2'
  # @@protoc_insertion_point(class_scope:proxy.ProxyReply)
  })
_sym_db.RegisterMessage(ProxyReply)

Proxy = _reflection.GeneratedProtocolMessageType('Proxy', (_message.Message,), {
  'DESCRIPTOR' : _PROXY,
  '__module__' : 'proto.proxy_pb2'
  # @@protoc_insertion_point(class_scope:proxy.Proxy)
  })
_sym_db.RegisterMessage(Proxy)


DESCRIPTOR._options = None

_PROXYAPI = _descriptor.ServiceDescriptor(
  name='ProxyApi',
  full_name='proxy.ProxyApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=419,
  serialized_end=483,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetProxies',
    full_name='proxy.ProxyApi.GetProxies',
    index=0,
    containing_service=None,
    input_type=_PROXYREQUEST,
    output_type=_PROXYREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PROXYAPI)

DESCRIPTOR.services_by_name['ProxyApi'] = _PROXYAPI

# @@protoc_insertion_point(module_scope)
