[tool.poetry]
name = "mb_excelexport_2csv"
version = "0.6.0"
description = "Parses an .xls excel file downloaded from ManageBac and converts to comma-deliminated csv. Particularly useful to convert to GSheets without having to use Excel."
authors = ["Adam Morris <classroomtechtools.ctt@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6.1"
click = "^8.0.3"
PyQt6 = "^6.2.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
mb_excelexport_2csv = "mb_excelexport_2csv.main:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
