
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-02T21:24:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a9cda4f363c0e3ba220d5dd0a99b197773dac6d6",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
