[tool.poetry]
name = "postgres-fixture"
version = "0.1.0"
description = ""
authors = ["peder2911 <pglandsverk@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.3"
SQLAlchemy = "^1.4.26"
psycopg2 = "^2.9.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
pg_fx = "postgres_fixture.postgres_fixture:postgres_fixture"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
