
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-02T13:20:20+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fffca10916ea1de23b57eaea830f28e5efbb793e",
 "version": "1.33"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
