[tool.poetry]
name = "colorsplash-common"
version = "0.3.1"
description = "A common set of classes for the ColorSplash project python components"
license = "MIT"
authors = ["Daniel Thurau <daniel.n.thurau@gmail.com>"]
readme = "README.md"
homepage = "https://thurau.io/colorsplash/"
repository = "https://github.com/DanielThurau/colorsplash-common"

[tools.poetry.urls]
"Bug Tracker" = "https://github.com/DanielThurau/colorsplash-common/issues"

[tool.poetry.dependencies]
python = "^3.8"
boto3 = "^1.19.3"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
