[tool.poetry]
name = "simple_status_client"
version = "0.1.3"
description = "A package for interacting with the Simple Status Server"
authors = ["Benjamin Smith <bravosierra99@gmail.com>"]
license = "GPL-3.0-or-later"
readme = "README.md"
homepage = "https://github.com/bravosierra99/SimpleStatusClient"
repository = "https://github.com/bravosierra99/SimpleStatusClient"
include = [
"LICENSE",
]

[tool.poetry.dependencies]
python = "^3.6.2"
requests = "^2.26.0"
yarl = "^1.6.3"
fastapi = "^0.68.1"

[tool.poetry.dev-dependencies]
black = "^21.8b0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black] 
line-length = 120 
target-version = ['py39']
include = '\.pyi?$' 
exclude = ''
