
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-02T09:44:57+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ff3a3c1284a9a4bffa5729ab657ad609c34a6d3",
 "version": "0.3.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
