
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-27T14:05:13-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bbeda7a824ae5cd8252813b6d762c87945ab4b29",
 "version": "0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
