# If any of these fields are missing in your config, then this config's
# fields replace them automatically

[CONFIG]
ASSIGNMENT_NAME = "Homework"         # For display in the output for the student
TOTAL_POINTS_POSSIBLE = 100          # Total points given for tests
POSSIBLE_SOURCE_FILE_STEMS = []      # At least one of these names must be in each submission's name. Empty means that we grade all submissions.
TIMEOUT = { "DEFAULT" = 1 }          # Student's program is terminated if it takes more than this time in seconds
TESTCASE_WEIGHTS = { "DEFAULT" = 1 } # A list of testcase_filename=maximum_result_percentage values.
SUBMISSION_PRECOMPILATION_ARGS = {}  # Extra arguments to be passed with each submission during pre-compilation
TESTCASE_PRECOMPILATION_ARGS = {}    # Extra arguments to be passed with each testcase during pre-compilation
TESTCASE_COMPILATION_ARGS = {}       # Extra arguments to be passed with each testcase during compilation
TESTCASE_RUNTIME_ARGS = {}           # Extra arguments to be passed to each testcase during runtime
GENERATE_RESULTS = true              # Generate results directory with a result file per student
STDOUT_ONLY_GRADING_ENABLED = false  # Grade in stdout-only mode (Requires 'Possible Source File Stems')
PARALLEL_GRADING_ENABLED = false     # Grade multiple submissions at once.

[GCC]
MEMORY_LEAK_DETECTION = false # if true, memory leak summary will be generated for each student submission
