[package]
name = "jst"
version = "0.1.0"
authors = ["kitagawa-hr <kitagawa@cancerscan.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "jst"
# "cdylib" is necessary to produce a shared library for Python to import from.
#
# Downstream Rust code (including code in `bin/`, `examples/`, and `tests/`) will not be able
# to `use string_sum;` unless the "rlib" or "lib" crate type is also included, e.g.:
# crate-type = ["cdylib", "rlib"]
crate-type = ["cdylib"]


[dependencies]
jsonschema-transpiler = "1.10.0"
pyo3 = { version = "0.14.5", features = ["extension-module"] }
serde_json = "1.0"
