[tool.poetry]
name = "jst"
version = "0.1.0"
description = ""
authors = ["kitagawa-hr <kitagawaht@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.6"


[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
maturin = "^0.11.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
