
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-29T05:06:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "775abe1783f20f3d2278bce8b97454fb2e15261d",
 "version": "0.5.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
