[tool.poetry]
name = "innertube"
version = "1.0.2"
description = "Python Client for Google's Private InnerTube API. Works with Youtube, YouTubeMusic etc."
authors = ["Tom Bulled <26026015+tombulled@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/tombulled/innertube"
repository = "https://github.com/tombulled/innertube"
keywords = ["youtube", "innertube", "python", "api"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.7.3"
requests = "^2.25.1"
addict = "^2.4.0"
furl = "^2.1.0"
parse = "^1.19.0"
toolz = "^0.11.1"
attrs = "^21.2.0"
# mime = {git = "https://github.com/tombulled/mime.git", rev = "main"}
# register = {git = "https://github.com/tombulled/register.git", rev = "main"}
# useragent = {git = "https://github.com/tombulled/useragent.git", rev = "main"}
# sets = {git = "https://github.com/tombulled/sets.git", rev = "main"}
# enumb = {git = "https://github.com/tombulled/enumb.git", rev = "main"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
