
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-02T16:46:27+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a2302294ceee4066935114177c35a6b817a4fbb",
 "version": "0.4.89"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
