[tool.poetry]
name = "ilia"
version = "0.1.0"
description = "a JSON Schema draft 2020-12 validation library"
license = "BSD-4-Clause"
authors = [ "Xavier Barbosa <clint.northwood@gmail.com>" ]
readme = "README.md"
homepage = "https://lab.errorist.xyz"
keywords = [ "validation", "json-schema" ]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development",
    "Topic :: Software Development :: Libraries",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.10"
types-dataclasses = "^0.6.1"
pytest-subtests = "^0.5.0"
httpx = { extras = [ "brotli", "http2" ], version = "^0.20.0" }

[tool.poetry.dev-dependencies]
black = "^21.9b0"
pytest = "^6.2.5"
mypy = { git = "ssh://git@github.com/python/mypy.git" }
isort = "^5.9.3"
flake8 = "^4.0.1"
rich = "^10.12.0"
pytest-httpserver = "^1.0.2"
flake8-cognitive-complexity = "^0.1.0"
flake8-bugbear = "^21.9.2"
pytest-cov = "^3.0.0"
jmespath = "^0.10.0"

[build-system]
requires = [ "poetry-core>=1.0.0" ]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--import-mode=importlib -vvv --cov --no-cov-on-fail"
filterwarnings = [ "ignore:A private pytest class or function was used.:pytest.PytestDeprecationWarning" ]

[tool.isort]
profile = "black"

[tool.coverage.run]
branch = true
source_pkgs = [ "ilia" ]

[tool.coverage.report]
exclude_lines = [ "pragma: no-cover", "def __repr__" ]
include = [ "src/**/*.py" ]
show_missing = true
