"""
    defektor OpenAPI Specification

    defektor controll aplication interface  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sob@dei.uc.pt
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import defektor_api
from defektor_api.model.injektion import Injektion
from defektor_api.model.system_type import SystemType
globals()['Injektion'] = Injektion
globals()['SystemType'] = SystemType
from defektor_api.model.plan import Plan


class TestPlan(unittest.TestCase):
    """Plan unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPlan(self):
        """Test Plan"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Plan()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
