"""
    defektor OpenAPI Specification

    defektor controll aplication interface  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sob@dei.uc.pt
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import defektor_api
from defektor_api.model.data_collector import DataCollector
from defektor_api.model.ijk import Ijk
from defektor_api.model.work_load import WorkLoad
globals()['DataCollector'] = DataCollector
globals()['Ijk'] = Ijk
globals()['WorkLoad'] = WorkLoad
from defektor_api.model.injektion import Injektion


class TestInjektion(unittest.TestCase):
    """Injektion unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInjektion(self):
        """Test Injektion"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Injektion()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
