"""
    defektor OpenAPI Specification

    defektor controll aplication interface  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sob@dei.uc.pt
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import defektor_api
from defektor_api.model.key_value import KeyValue
from defektor_api.model.system_type import SystemType
globals()['KeyValue'] = KeyValue
globals()['SystemType'] = SystemType
from defektor_api.model.system_config import SystemConfig


class TestSystemConfig(unittest.TestCase):
    """SystemConfig unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSystemConfig(self):
        """Test SystemConfig"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SystemConfig()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
