
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-27T16:18:46+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "595f98b6ef58423730a4caf8c16681e400f9b8f9",
 "version": "0.0.62"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
