{% set name = "mat_discover" %}
{% set version = "1.3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mat_discover-{{ version }}.tar.gz
  sha256: ad57226534505c83a9dea163f74bcb83783e09e406dbc22b88476ec6c70465e1

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

  noarch: python
requirements:
  host:
    - pip
    - flit
    - python
  run:
    - chem_wasserstein >=1.0.3
    - cudatoolkit <11.4
    - pytorch >=1.9.0
    - python-kaleido
    - crabnet >=1.0.6
    - cython
    - dill
    - hdbscan
    - matplotlib-base >=3.4.3
    - numba >=0.53.1
    - pandas
    - plotly
    - pqdm
    - python
    - scikit-learn
    - scipy
    - seaborn
    - tqdm
    - umap-learn

test:
  imports:
    - mat_discover
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mat_discover/
  summary: Data-driven materials discovery based on composition.
  dev_url: https://github.com/sparks-baird/mat_discover
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgbaird
