# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Pipeline": "00_cli.ipynb",
         "justautomate_cli": "00_cli.ipynb",
         "get_new_secret": "02_new_secrets.ipynb"}

modules = ["cli.py",
           "tools/security.py"]

doc_url = "https://justautomate.github.io/justautomate/"

git_url = "https://github.com/justautomate-co/justautomate"

def custom_doc_links(name): return None
