[tool.poetry]
name = "fungi"
version = "0.1.0"
description = "A set of common utilities for iNotify (based on iNotify Simple) that makes it a little easier to work with"
authors = ["Eugene Kovalev <eugene@kovalev.systems>"]
classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
        "Operating System :: OS Independent",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Programming Language :: Python :: 3.8",
]
documentation="https://gitlab.com/abraxos/fungi"
repository="https://gitlab.com/abraxos/fungi"
readme="README.md"
license="GPL-3.0-only"

[tool.poetry.dependencies]
python = "^3.6"
inotify-simple = "^1.3.5"
psutil = "^5.8.0"
typeguard = "^2.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-cov = "^2.11.1"
pylint = "^2.6.0"
mypy = "^0.790"
flake8 = "^3.8.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
