variables:
  CIBW_BUILD: cp37-* cp38-* cp39-* cp310-*
  CIBW_ARCHS_LINUX: "auto, aarch64"

resources:
  repositories:
  - repository: OpenAstronomy
    type: github
    endpoint: liberfa
    name: OpenAstronomy/azure-pipelines-templates
    ref: master

trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'

jobs:

# The following is the configuration to automatically release a new version
# to PyPI if a tag is pushed - for more details, see:
# https://openastronomy-azure-pipelines.readthedocs.io/en/latest/publish.html

- template: publish.yml@OpenAstronomy
  parameters:
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/v') }}:
      pypi_connection_name: 'pypi_endpoint'
    test_extras: test
    test_command: pytest --pyargs erfa
    targets:
    - sdist
    - wheels_cp*-manylinux_i686
    - wheels_cp*-manylinux_x86_64
    - wheels_cp37-musllinux_x86_64
    - wheels_cp38-musllinux_x86_64
    - wheels_cp39-musllinux_x86_64
    - wheels_cp310-musllinux_x86_64
    - wheels_cp37-manylinux_aarch64
    - wheels_cp38-manylinux_aarch64
    - wheels_cp39-manylinux_aarch64
    - wheels_cp310-manylinux_aarch64
    - wheels_macos
    - wheels_windows
