{% set name = "mat_discover" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mat_discover-{{ version }}.tar.gz
  sha256: db4282b19dee8d851edc9dc1fc126aa0e670f0d55f3d4a718f8b23dd5fd273f0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
    - flit
  run:
    - elmd ==0.4.8 #pip --> sgbaird conda channel
    - hdbscan
    - cython # for hdbscan 0.8.27 (or similar?)
    - joblib
    - python-kaleido
    - matplotlib >=3.4.3
    - numba >=0.53.1
    - pandas
    - plotly
    - tqdm
    - pqdm ==0.1.0 #pip --> sgbaird conda channel
    - psutil
    - pymatgen
    - python
    - scikit-learn
    - scipy
    - seaborn
    - umap-learn
    - pytorch >=1.9.* #==1.9.1
    - cudatoolkit ==11.3.*
    - dill

test:
  imports:
    - mat_discover
    - mat_discover.CrabNet
    - mat_discover.ElM2D
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mat_discover/
  summary: Data-driven materials discovery based on composition.
  dev_url: https://github.com/sparks-baird/mat_discover
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgbaird
