
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-28T20:47:34+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "831e5d7e78522cb73adc30404033138e7d5102ec",
 "version": "3.0.0dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
