# Generated by Django 3.0.5 on 2020-05-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_rds_iam_auth', '0018_auto_20200502_1117'),
    ]

    operations = [
        migrations.RunSQL("""
                   CREATE POLICY tenant_table_policy ON api_tenant
                        USING (ibrag_user_has_tenant(id))
                        WITH CHECK (ibrag_user_has_tenant(id) AND
                            (owner_id = cast(current_user as varchar) OR
                             ibrag_user_has_role('tenant_damin')));
                """, reverse_sql="drop policy tenant_table_policy on table api_tenant;"),

    ]
