"""
    Nomad CBEC

    This is the API descriptor for the Nomad CBEC, responsible for CBEC customer ID check. Developed by `Samarkand Global <https://samarkand.global>`_  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


import unittest

import nomad_cbec_id_cli
from nomad_cbec_id_cli.api.user_api import UserApi  # noqa: E501


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_id_check(self):
        """Test case for id_check

        idCheck  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
