# coding: utf-8

"""
    Modern Logic Api

    Manage and version your customer decision logic outside of your codebase  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@usemodernlogic.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ExecutionItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'date_time_executed': 'datetime',
        'workflow_id': 'int'
    }

    attribute_map = {
        'id': 'id',
        'date_time_executed': 'dateTimeExecuted',
        'workflow_id': 'workflowId'
    }

    def __init__(self, id=None, date_time_executed=None, workflow_id=None):  # noqa: E501
        """ExecutionItem - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._date_time_executed = None
        self._workflow_id = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if date_time_executed is not None:
            self.date_time_executed = date_time_executed
        if workflow_id is not None:
            self.workflow_id = workflow_id

    @property
    def id(self):
        """Gets the id of this ExecutionItem.  # noqa: E501


        :return: The id of this ExecutionItem.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ExecutionItem.


        :param id: The id of this ExecutionItem.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def date_time_executed(self):
        """Gets the date_time_executed of this ExecutionItem.  # noqa: E501

        When the execution happened  # noqa: E501

        :return: The date_time_executed of this ExecutionItem.  # noqa: E501
        :rtype: datetime
        """
        return self._date_time_executed

    @date_time_executed.setter
    def date_time_executed(self, date_time_executed):
        """Sets the date_time_executed of this ExecutionItem.

        When the execution happened  # noqa: E501

        :param date_time_executed: The date_time_executed of this ExecutionItem.  # noqa: E501
        :type: datetime
        """

        self._date_time_executed = date_time_executed

    @property
    def workflow_id(self):
        """Gets the workflow_id of this ExecutionItem.  # noqa: E501


        :return: The workflow_id of this ExecutionItem.  # noqa: E501
        :rtype: int
        """
        return self._workflow_id

    @workflow_id.setter
    def workflow_id(self, workflow_id):
        """Sets the workflow_id of this ExecutionItem.


        :param workflow_id: The workflow_id of this ExecutionItem.  # noqa: E501
        :type: int
        """

        self._workflow_id = workflow_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExecutionItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExecutionItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
