# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pw_log/proto/log.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pw_tokenizer.proto import options_pb2 as pw__tokenizer_dot_proto_dot_options__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pw_log/proto/log.proto',
  package='pw.log',
  syntax='proto3',
  serialized_options=b'B\003Log',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x16pw_log/proto/log.proto\x12\x06pw.log\x1a pw_tokenizer/proto/options.proto\"\xb6\x01\n\x08LogEntry\x12\x1a\n\x07message\x18\x01 \x01(\x0c\x42\x04\x80\xaf&\x00H\x01\x88\x01\x01\x12\x17\n\nline_level\x18\x02 \x01(\rH\x02\x88\x01\x01\x12\x12\n\x05\x66lags\x18\x03 \x01(\rH\x03\x88\x01\x01\x12\x13\n\ttimestamp\x18\x04 \x01(\x03H\x00\x12\x1f\n\x15time_since_last_entry\x18\x05 \x01(\x03H\x00\x42\x06\n\x04timeB\n\n\x08_messageB\r\n\x0b_line_levelB\x08\n\x06_flags\"\x0c\n\nLogRequest\"/\n\nLogEntries\x12!\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x10.pw.log.LogEntry2:\n\x04Logs\x12\x32\n\x06Listen\x12\x12.pw.log.LogRequest\x1a\x12.pw.log.LogEntries0\x01\x42\x05\x42\x03Logb\x06proto3'
  ,
  dependencies=[pw__tokenizer_dot_proto_dot_options__pb2.DESCRIPTOR,])




_LOGENTRY = _descriptor.Descriptor(
  name='LogEntry',
  full_name='pw.log.LogEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='pw.log.LogEntry.message', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\200\257&\000', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='line_level', full_name='pw.log.LogEntry.line_level', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='flags', full_name='pw.log.LogEntry.flags', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='pw.log.LogEntry.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_since_last_entry', full_name='pw.log.LogEntry.time_since_last_entry', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='time', full_name='pw.log.LogEntry.time',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_message', full_name='pw.log.LogEntry._message',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_line_level', full_name='pw.log.LogEntry._line_level',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_flags', full_name='pw.log.LogEntry._flags',
      index=3, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=69,
  serialized_end=251,
)


_LOGREQUEST = _descriptor.Descriptor(
  name='LogRequest',
  full_name='pw.log.LogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=253,
  serialized_end=265,
)


_LOGENTRIES = _descriptor.Descriptor(
  name='LogEntries',
  full_name='pw.log.LogEntries',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='pw.log.LogEntries.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=314,
)

_LOGENTRY.oneofs_by_name['time'].fields.append(
  _LOGENTRY.fields_by_name['timestamp'])
_LOGENTRY.fields_by_name['timestamp'].containing_oneof = _LOGENTRY.oneofs_by_name['time']
_LOGENTRY.oneofs_by_name['time'].fields.append(
  _LOGENTRY.fields_by_name['time_since_last_entry'])
_LOGENTRY.fields_by_name['time_since_last_entry'].containing_oneof = _LOGENTRY.oneofs_by_name['time']
_LOGENTRY.oneofs_by_name['_message'].fields.append(
  _LOGENTRY.fields_by_name['message'])
_LOGENTRY.fields_by_name['message'].containing_oneof = _LOGENTRY.oneofs_by_name['_message']
_LOGENTRY.oneofs_by_name['_line_level'].fields.append(
  _LOGENTRY.fields_by_name['line_level'])
_LOGENTRY.fields_by_name['line_level'].containing_oneof = _LOGENTRY.oneofs_by_name['_line_level']
_LOGENTRY.oneofs_by_name['_flags'].fields.append(
  _LOGENTRY.fields_by_name['flags'])
_LOGENTRY.fields_by_name['flags'].containing_oneof = _LOGENTRY.oneofs_by_name['_flags']
_LOGENTRIES.fields_by_name['entries'].message_type = _LOGENTRY
DESCRIPTOR.message_types_by_name['LogEntry'] = _LOGENTRY
DESCRIPTOR.message_types_by_name['LogRequest'] = _LOGREQUEST
DESCRIPTOR.message_types_by_name['LogEntries'] = _LOGENTRIES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LogEntry = _reflection.GeneratedProtocolMessageType('LogEntry', (_message.Message,), {
  'DESCRIPTOR' : _LOGENTRY,
  '__module__' : 'pw_log.proto.log_pb2'
  # @@protoc_insertion_point(class_scope:pw.log.LogEntry)
  })
_sym_db.RegisterMessage(LogEntry)

LogRequest = _reflection.GeneratedProtocolMessageType('LogRequest', (_message.Message,), {
  'DESCRIPTOR' : _LOGREQUEST,
  '__module__' : 'pw_log.proto.log_pb2'
  # @@protoc_insertion_point(class_scope:pw.log.LogRequest)
  })
_sym_db.RegisterMessage(LogRequest)

LogEntries = _reflection.GeneratedProtocolMessageType('LogEntries', (_message.Message,), {
  'DESCRIPTOR' : _LOGENTRIES,
  '__module__' : 'pw_log.proto.log_pb2'
  # @@protoc_insertion_point(class_scope:pw.log.LogEntries)
  })
_sym_db.RegisterMessage(LogEntries)


DESCRIPTOR._options = None
_LOGENTRY.fields_by_name['message']._options = None

_LOGS = _descriptor.ServiceDescriptor(
  name='Logs',
  full_name='pw.log.Logs',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=316,
  serialized_end=374,
  methods=[
  _descriptor.MethodDescriptor(
    name='Listen',
    full_name='pw.log.Logs.Listen',
    index=0,
    containing_service=None,
    input_type=_LOGREQUEST,
    output_type=_LOGENTRIES,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOGS)

DESCRIPTOR.services_by_name['Logs'] = _LOGS

# @@protoc_insertion_point(module_scope)
