[tool.poetry]
name = "gcphelpers"
version = "0.0.10"
description = "Helpers for GCP functions"
authors = ["Alex Orfanos <alexandros@mailerlite.com>"]

[tool.poetry.dependencies]
python = "^3.8"
google-cloud-secret-manager = "^2.7.2"
google-cloud-storage = "^1.42.3"
pre-commit = "^2.15.0"
prometheus-client = "^0.11.0"
slack-sdk = "^3.11.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
