
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-05T11:13:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9917d07839e96067a4d379c144d0f7e7ffc90922",
 "version": "2.5.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
