
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-28T14:12:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "15ea47fd6d04fdfa36eabaaa39556d5e5bc2d234",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
