
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-28T22:36:02-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "0ee0ad4ecab60d175805e457203e0ed681382ff5",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
