[tool.black]
line-length = 120
target-version = ['py39']
include = '\.py$'
exclude = '''
(
      \.git
    | \.venv
    | /__pycache__/
)
'''

[tool.pylint.master]
ignore-paths = [
    "^build/.*$",
    "^dist/.*$",
]

[tool.pylint.format]
max-line-length = 120
max-module-lines = 1000


[tool.pylint.messages_control]
disable = []

[tool.pylint.similarities]
ignore-imports = "yes"
min-similarity-lines = 5

[tool.pylint.basic]
good-names = ["i", "j", "k", "v", "e", "ui", "by"]
