
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-25T12:06:24-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "414f73c91cdd151cf6eebbceb2dae16422adcd08",
 "version": "0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
