
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-26T10:56:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "619042a55160ff98ca93097307f8af89a270745b",
 "version": "v0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
