root: ./docs/

redirects:
    quick-start-faq: ./resources/faq.md
    resources/quick-start-faq: ./resources/faq.md
    subsetting-your-test-runs: ./actions/subsetting-your-test-runs.md
    test-runners/bazel: ./resources/integrations/bazel.md
    test-runners/behave: ./resources/integrations/behave.md
    test-runners/ctest: ./resources/integrations/ctest.md
    test-runners/cypress: ./resources/integrations/cypress.md
    test-runners/file: ./resources/integrations/file.md
    test-runners/googletest: ./resources/integrations/googletest.md
    test-runners/go-test: ./resources/integrations/go-test.md
    test-runners/gradle: ./resources/integrations/gradle.md
    test-runners/maven: ./resources/integrations/maven.md
    test-runners/minitest: ./resources/integrations/minitest.md
    test-runners/nose: ./resources/integrations/nose.md
    test-runners/pytest: ./resources/integrations/pytest.md
    test-runners/robot: ./resources/integrations/robot.md
