[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "matplotlib",
    "wxpython",
    "pyopengl",
    "pandas",
    "scipy",
    "pillow",
    "owslib",
	"cython",
	"pyproj"
]
build-backend = "setuptools.build_meta"