
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-02T17:34:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "e51ec078b586f2ca5da2f5aa2199773549d77b91",
 "version": "0.4.92"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
