[tool.poetry]
name = "amora"
version = "0.1.0"
description = "Amora Data Build Tool"
authors = ["diogommartins <diogommartins.dev@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9.6"
pandas = "^1.3.0"
jupyter = "^1.0.0"
numpy = "^1.21.1"
matplotlib = "^3.4.2"
sqlmodel = "^0.0.4"
sqlalchemy-bigquery = "1.2.0"
networkx = {extras = ["default", "extra"], version = "^2.6.3"}
dbt = "^0.20.2"
typer = {extras = ["all"], version = "^0.4.0"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
pytest-env = "^0.6.2"
pytest-cov = "^3.0.0"
black = "^21.9b0"
mypy = "^0.910"
lxml = "^4.6.3"
twine = "^3.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
