
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-29T06:53:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "efb784bd379d17e361b6715dfe3350d52b3cd575",
 "version": "0.9.20"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
