
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-02T16:56:47+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "03c79fff670a6c1cea26c25ad9b53291edf9744c",
 "version": "0.4.90"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
