
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-01T23:08:03+0100",
 "dirty": true,
 "error": null,
 "full-revisionid": "3c98c36a966b18efd43ee783913e207f5b8b037a",
 "version": "0.3.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
