# -*- coding: utf-8 -*-
"""QNAP QSW Constants."""

ATTR_ANOMALY = "anomaly"
ATTR_COMMAND = "command"
ATTR_DATA = "data"
ATTR_ERROR_CODE = "error_code"
ATTR_ERROR_MESSAGE = "error_message"
ATTR_FAN1SPEED = "Fan1Speed"
ATTR_FAN2SPEED = "Fan2Speed"
ATTR_IDX = "idx"
ATTR_MAC = "MacAddr"
ATTR_MESSAGE = "message"
ATTR_MODEL = "Model"
ATTR_NEWER = "newer"
ATTR_NUM_PORTS = "PortNum"
ATTR_NUMBER = "number"
ATTR_PASSWORD = "password"
ATTR_PRODUCT = "Product"
ATTR_REBOOT = "reboot"
ATTR_RESULT = "result"
ATTR_SERIAL = "SerialNumber"
ATTR_TEMP = "SwitchTemp"
ATTR_TEMP_MAX = "MaxSwitchTemp"
ATTR_USERNAME = "username"
ATTR_UPTIME = "UpTime"
ATTR_VERSION = "version"

API_AUTHORIZATION = "Authorization"
API_DEBUG = False
API_QSW_ID = "QSW_ID"
API_QSW_LANG = "QSW_LANG"
API_TIMEOUT = 15
API_URI = "api"
API_URI_V1 = "v1"
API_URI_FULL = f"{API_URI}/{API_URI_V1}"
API_VERIFY = False

DATA_CONDITION_ANOMALY = "condition_anomaly"
DATA_CONDITION_MESSAGE = "condition_message"
DATA_CONFIG_URL = "config_url"
DATA_FIRMWARE = "firmware"
DATA_FAN_COUNT = "fan_count"
DATA_FAN1_SPEED = "fan1_speed"
DATA_FAN2_SPEED = "fan2_speed"
DATA_MAC_ADDR = "mac_addr"
DATA_MODEL = "model"
DATA_PRODUCT = "product"
DATA_SERIAL = "serial"
DATA_TEMP = "temp"
DATA_TEMP_MAX = "temp_max"
DATA_UPDATE = "update"
DATA_UPDATE_VERSION = "update_version"
DATA_UPTIME = "uptime"
DATA_UPTIME_SECONDS = "uptime_seconds"

UPTIME_DELTA = 5
