[tool.poetry]
name = "pipeline-ai"
version = "0.0.4a"
description = "Yay ml pipelines"
authors = ["Paul Hetherington <paul@getneuro.ai>"]
packages = [{include="src/*"}]

[tool.poetry.dependencies]
python = "^3.7"
black = "^21.10b0"
dill = "^0.3.4"
transformers = "^4.12.2"
pydantic = "^1.8.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
