[tool.poetry]
name = "xarray-dataclasses"
version = "0.6.1"
description = "xarray extension for typed DataArray and Dataset creation"
authors = ["Akio Taniguchi <taniguchi@a.phys.nagoya-u.ac.jp>"]
keywords = ["xarray", "dataclass", "dataarray", "dataset", "typing"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/astropenguin/xarray-dataclasses/"
documentation = "https://astropenguin.github.io/xarray-dataclasses/"

[tool.poetry.dependencies]
python = ">=3.7, <3.10"
morecopy = "^0.2"
numpy = "^1.19"
typing-extensions = "^3.10"
xarray = ">=0.15, <1.0"

[tool.poetry.dev-dependencies]
black = "^21.9b"
flake8 = "^4.0"
ipython = "^7.28"
pydata-sphinx-theme = "^0.7"
pytest = "^6.2"
sphinx = "^4.2"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"
