[tool.poetry]
name = "infpath"
version = "1.2.0"
description = "infpath('PATH', 'OPTION') - For Using."
authors = ["adamsonScripts"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
