
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-31T03:08:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "6546ef51c21a410bd54c8ad2f8a8ab0377d9fa48",
 "version": "0.7.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
