#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['tanjun']

package_data = \
{'': ['*']}

install_requires = \
['hikari~=2.0.0.dev103']

extras_require = \
{'docs': ['pdoc~=8.0'],
 'flake8': ['flake8~=4.0',
            'flake8-bandit~=2.1',
            'flake8-black~=0.2.3',
            'flake8-broken-line~=0.4.0',
            'flake8-builtins~=1.5',
            'flake8-coding~=1.3',
            'flake8-comprehensions~=3.7',
            'flake8-deprecated~=1.3',
            'flake8-executable~=2.1',
            'flake8-fixme~=1.1',
            'flake8-functions==0.0.6',
            'flake8-html~=0.4.1',
            'flake8-if-statements~=0.1.0',
            'flake8-isort~=4.1',
            'flake8-mutable~=1.2',
            'flake8-pep3101~=1.3',
            'flake8-print~=4.0',
            'flake8-printf-formatting~=1.1',
            'flake8-pytest-style~=1.5',
            'flake8-raise==0.0.5'],
 'lint': ['codespell~=2.1'],
 'publish': ['flit~=3.3'],
 'reformat': ['black~=21.7b0', 'isort~=5.9'],
 'tests': ['pytest~=6.2', 'pytest-asyncio~=0.16.0', 'pytest-cov~=3.0'],
 'type_checking': ['pyright==0.0.10']}

setup(name='hikari-tanjun',
      version='2.1.3a1',
      description='A flexible command framework designed to extend Hikari.',
      author=None,
      author_email='Faster Speeding <lucina@lmbyrne.dev>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
      extras_require=extras_require,
      python_requires='>=3.9.0,<3.12',
     )
