[tool.poetry]
name = "dgraph-orm"
version = "0.1.39"
description = ""
authors = ["Jeremy Berman <jerber@sas.upenn.edu>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
pydantic = {extras = ["dotenv"], version = "^1.8.2"}
devtools = "^0.8.0"
fastapi = "^0.70.0"
black = "^21.9b0"
httpx = "^0.19.0"
graphql-core = "^3.1.6"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
