# Generated by Django 3.2 on 2021-10-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slunic', '0004_auto_20211026_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='bookmark_count',
            new_name='book_count',
        ),
        migrations.RemoveField(
            model_name='page',
            name='clap_count',
        ),
        migrations.RemoveField(
            model_name='page',
            name='downvote_count',
        ),
        migrations.RemoveField(
            model_name='page',
            name='duplicate_count',
        ),
        migrations.RemoveField(
            model_name='page',
            name='subscriber_count',
        ),
        migrations.RemoveField(
            model_name='page',
            name='upvote_count',
        ),
        migrations.AddField(
            model_name='page',
            name='accept_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='answer_count',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='reply_count',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='page',
            name='subs_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='thread_votecount',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='page',
            name='view_count',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='type',
            field=models.IntegerField(blank=True, choices=[(None, '(unknown)'), (99, 'empty'), (0, 'up vote'), (1, 'down vote'), (3, 'bookmark'), (4, 'accept'), (5, 'spam')], db_index=True, default='(unknown)', null=True),
        ),
    ]
