# Generated by Django 3.2 on 2021-10-27 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slunic', '0007_page_vote_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.IntegerField(choices=[(0, 'comment'), (1, 'answer')], default=0),
        ),
    ]
