# Generated by Django 3.2 on 2021-10-27 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slunic', '0008_comment_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
