# Generated by Django 3.2 on 2021-10-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slunic', '0009_delete_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_spam',
            field=models.BooleanField(default=False),
        ),
    ]
