# Generated by Django 3.2 on 2021-10-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slunic', '0010_comment_is_spam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='state',
        ),
        migrations.AddField(
            model_name='page',
            name='state',
            field=models.IntegerField(choices=[(1, 'open'), (2, 'off topic'), (3, 'duplicate'), (4, 'solved'), (5, 'closed')], db_index=True, default=1),
        ),
    ]
