# Generated by Django 3.2 on 2021-10-28 21:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slunic', '0011_auto_20211028_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='diff',
            name='original',
            field=models.TextField(blank=True, help_text='original page content before edited.', null=True, verbose_name='content'),
        ),
        migrations.AddField(
            model_name='page',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(blank=True, null=True)),
                ('action', models.IntegerField(choices=[(0, 'Moderate'), (1, 'Create'), (2, 'Edit'), (3, 'Login'), (4, 'Logout'), (5, 'Classify'), (6, 'Default')], db_index=True, default=6)),
                ('text', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slunic.page')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
