# Generated by Django 3.2 on 2021-10-25 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slunic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='has_diff',
            field=models.BooleanField(default=False, verbose_name='diff status'),
        ),
        migrations.AlterField(
            model_name='diff',
            name='page',
            field=models.ForeignKey(help_text='Page, This diff belongs to', on_delete=django.db.models.deletion.CASCADE, to='slunic.page'),
        ),
    ]
