# Generated by Django 3.2 on 2021-10-26 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slunic', '0002_auto_20211025_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='vote_count',
            new_name='downvote_count',
        ),
        migrations.AddField(
            model_name='page',
            name='upvote_count',
            field=models.IntegerField(default=0),
        ),
    ]
