# Generated by Django 3.2 on 2021-10-26 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slunic', '0003_auto_20211026_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='thread_votecount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='type',
            field=models.IntegerField(blank=True, choices=[(None, '(unknown)'), (99, 'empty'), (0, 'up vote'), (1, 'down vote'), (2, 'clap'), (3, 'bookmark'), (4, 'accept'), (5, 'spam'), (6, 'duplicate'), (7, 'subscribe')], db_index=True, default='(unknown)', null=True),
        ),
    ]
