# Generated by Django 3.2 on 2021-10-26 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slunic', '0005_auto_20211026_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.IntegerField(choices=[(1, 'reader'), (2, 'moderator'), (3, 'manager'), (4, 'blogger')], db_index=True, default=1, verbose_name='role'),
        ),
    ]
