# Generated by Django 3.2 on 2021-10-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slunic', '0006_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='vote_count',
            field=models.IntegerField(blank=True, db_index=True, default=0),
        ),
    ]
