# Generated by Django 3.2 on 2021-10-29 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slunic', '0012_auto_20211028_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='allow_comments',
            new_name='comment_enabled',
        ),
    ]
