from io import StringIO

def encode_json(configs: dict, ostream: StringIO) -> None: ...
def encode_yaml(configs: dict, ostream: StringIO) -> None: ...
def encode_ini(configs: dict, ostream: StringIO) -> None: ...
