# JUWELS YAML CONFIGURATION FILE

# basic setup
name: juwels
account: esmtst
jobtype: compute
accounting: true

# default settings for compiler, mpi and I/O libs
#compiler_mpi: intel2019_impi2019
#iolibraries: system_libs
# for FOCI/FOCIOIFS use
compiler_mpi: intel2019_parastation
iolibraries: geomar_libs

# slurm setup
batch_system: slurm
logical_cpus_per_core: 2
threads_per_core: 1
launcher_flags: "-l "

# set default for hyperthreading_flag
hyperthreading_flag: "--ntasks-per-core=1"

use_hyperthreading: False
choose_use_hyperthreading:
        "1":
                hyperthreading_flag: ""
        True:
                hyperthreading_flag: ""
        "0":
                hyperthreading_flag: "--ntasks-per-core=1"
        False:
                hyperthreading_flag: "--ntasks-per-core=1"

sh_interpreter: "/usr/bin/bash"

# pool directories
# TODO: cleanup the pool / focipool logic
pool_dir:  "/pool/data/not/available/on/juwels"
pool_directories:
        pool: "/pool/data/not/available/on/juwels"
        focipool: "/p/project/hirace/foci_input2"

# choose block
choose_jobtype:
        tidy_and_resubmit:
                partition: devel
        post:
                partition: devel
        compute:
                partition: devel

choose_partition:
        batch:
                cores_per_node: 24
        devel:
                cores_per_node: 24

# basic modules and export vars needed
# for all compiler and I/O settings
module_actions:
        - "--force purge"
        - "use /gpfs/software/juwels/otherstages"

export_vars:
        LC_ALL: en_US.UTF-8

# choose compiler and MPI implementation
choose_compiler_mpi:

   intel2019_impi2019:
      add_module_actions:
         - "load Stages/Devel-2019a"
         - "load Intel/2019.5.281-GCC-8.3.0"
         - "load IntelMPI/2019.6.154"
         - "load CMake"
         - "load Python/3.6.8"
         - "load imkl/2019.3.199"
         #TODO check if we need perl
         #- "load Perl/5.28.1"
      # FOCI needs the release_mt version of intel mpi
      choose_general.setup_name:
         foci:
            add_module_actions:
               - "source /gpfs/software/juwels/stages/Devel-2019a/software/impi/2019.6.154-iccifort-2019.3.199-GCC-8.3.0/bin/mpivars.sh release_mt"
      add_export_vars:
         FC: mpiifort
         F77: mpiifort
         MPIFC: mpiifort
         FCFLAGS: -free
         CC: mpiicc
         CXX: mpiicpc
         MPIROOT: "\"$(mpiifort -show | perl -lne 'm{ -I(.*?)/include } and print $1')\""
         MPI_LIB: "\"$(mpiifort -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')\""

   intel2019_parastation:
      add_module_actions:
         - "load Stages/Devel-2019a"
         - "load Intel/2019.5.281-GCC-8.3.0"
         - "load ParaStationMPI/5.4.4-1-mt"
         - "load CMake"
         - "load Python/3.6.8"
         - "load imkl/2019.3.199"
         #TODO check if we need perl
         #- "load Perl/5.28.1"
      add_export_vars:
         FC: mpifort
         F77: mpifort
         MPIFC: mpifort
         FCFLAGS: -free
         CC: mpicc
         CXX: mpic++
         MPIROOT: "\"$(mpifort -show | perl -lne 'm{ -I(.*?)/include } and print $1')\""
         MPI_LIB: "\"$(mpifort -show |sed -e 's/^[^ ]*//' -e 's/-[I][^ ]*//g')\""

choose_iolibraries:

    system_libs:
       # TODO: find the correct libraries and dependencies
       add_module_actions:
         - "load netCDF"
    geomar_libs:
       choose_compiler_mpi:
          intel2019_impi2019:
             add_export_vars:
                IO_LIB_ROOT: $PROJECT/HPC_libraries/intel2019.3.199_impi2019.6.154_20200703
                PATH: $IO_LIB_ROOT/bin:$PATH
                LD_LIBRARY_PATH: $IO_LIB_ROOT/lib:$LD_LIBRARY_PATH

                SZIPROOT: $IO_LIB_ROOT
                HDF5ROOT: $IO_LIB_ROOT
                HDF5_ROOT: $HDF5ROOT
                NETCDFROOT: $IO_LIB_ROOT
                NETCDFFROOT: $IO_LIB_ROOT
                ECCODESROOT: $IO_LIB_ROOT

                HDF5_C_INCLUDE_DIRECTORIES: $HDF5_ROOT/include
                NETCDF_Fortran_INCLUDE_DIRECTORIES: $NETCDFFROOT/include
                NETCDF_C_INCLUDE_DIRECTORIES: $NETCDFROOT/include
                NETCDF_CXX_INCLUDE_DIRECTORIES: $NETCDFROOT/include
                OASIS3MCT_FC_LIB: '"-L$NETCDFFROOT/lib -lnetcdff"'
          intel2019_parastation:
             add_export_vars:
                IO_LIB_ROOT: $PROJECT/HPC_libraries/intel2019.5.281_parastation_5.4.4-1-mt_20201113
                PATH: $IO_LIB_ROOT/bin:$PATH
                LD_LIBRARY_PATH: $IO_LIB_ROOT/lib:$LD_LIBRARY_PATH

                SZIPROOT: $IO_LIB_ROOT
                HDF5ROOT: $IO_LIB_ROOT
                HDF5_ROOT: $HDF5ROOT
                NETCDFROOT: $IO_LIB_ROOT
                NETCDFFROOT: $IO_LIB_ROOT
                ECCODESROOT: $IO_LIB_ROOT

                HDF5_C_INCLUDE_DIRECTORIES: $HDF5_ROOT/include
                NETCDF_Fortran_INCLUDE_DIRECTORIES: $NETCDFFROOT/include
                NETCDF_C_INCLUDE_DIRECTORIES: $NETCDFROOT/include
                NETCDF_CXX_INCLUDE_DIRECTORIES: $NETCDFROOT/include
                OASIS3MCT_FC_LIB: '"-L$NETCDFFROOT/lib -lnetcdff"'
       #add_export_vars:
# some yamls use computer.fc, etc to identify the compiler, so we need to add them
fc: "$FC"
cc: "$CC"
mpifc: "$MPIFC"
mpicc: "$MPICC"
cxx: "$CXX"

further_reading:
        - batch_system/slurm.yaml

