"""
    defektor OpenAPI Specification

    defektor controll aplication interface  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: sob@dei.uc.pt
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import defektor_api
from defektor_api.model.docker_image import DockerImage


class TestDockerImage(unittest.TestCase):
    """DockerImage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDockerImage(self):
        """Test DockerImage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DockerImage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
