"""
    Nomad CBEC

    This is the API descriptor for the Nomad CBEC, responsible for CBEC customer ID check. Developed by `Samarkand Global <https://samarkand.global>`_  # noqa: E501

    The version of the OpenAPI document: 1.5.0
    Contact: paul@samarkand.global
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import nomad_cbec_id_cli
from nomad_cbec_id_cli.model.api_response_data import ApiResponseData
globals()['ApiResponseData'] = ApiResponseData
from nomad_cbec_id_cli.model.api_response import ApiResponse


class TestApiResponse(unittest.TestCase):
    """ApiResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiResponse(self):
        """Test ApiResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApiResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
