[tool.poetry]
name = "x-scaffold"
version = "0.3.0"
description = ""
authors = ["Daniel Clayton <dclayton@godaddy.com>"]
license = "MIT"
packages = [
    { include = "xscaffold" }
]

[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^5.4.1"
Jinja2 = "^3.0.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
xscaffold = 'xscaffold.xscaffold:main'