class Node: ...

class Identifier(Node):
    def __new__(cls, value):
        return str.__new__(cls, value)

class URIRef(Identifier): ...
class BNode(Identifier): ...
class Literal(Identifier): ...
