
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-01T11:10:02+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "33ecdb11816b3ab8e7baf4070284c07ed32f09b0",
 "version": "0.7.1.post.dev126"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
