[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "maghsoodtest"
authors = [{name = "maghsood026", email = "maghsood95@gmail.com"}]
dynamic = ["version", "description"]
requires-python = ">=3.7"
