
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-27T15:00:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "b34b3837b87b0ce177e13c1d8c530ad0ff6bb5cf",
 "version": "v0.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
