
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-30T12:40:02+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc7cd4c9c98ee34e9d3002430c41d428729c0792",
 "version": "2.2.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
