[tool.poetry]
name = "d2b-compile"
version = "1.1.0"
description = "compile-dcm2bids-config plugin for the d2b package"
authors = ["Alec Ross <alexander.w.rosss@gmail.com>"]

readme = "README.md"

keywords = ["neuroscience", "neuroimaging", "bids", "plugin", "d2b"]

homepage = "https://github.com/d2b-dev/d2b-compile"
repository = "https://github.com/d2b-dev/d2b-compile"
documentation = "https://github.com/d2b-dev/d2b-compile"

classifiers = [
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Operating System :: MacOS",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Utilities",
    "Typing :: Typed",
]

[tool.poetry.dependencies]
python = "^3.8"
d2b = "^1.0.0"
compile-dcm2bids-config = "^1.4.3"

[tool.poetry.dev-dependencies]
black = "^21.8b0"
flake8 = "^3.9.2"
pylint = "^2.10.2"
reorder-python-imports = "^2.6.0"
pre-commit = "^2.15.0"
bump2version = "^1.0.1"

[tool.poetry.plugins.d2b]
"compile" = "d2b_compile"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
