
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-28T13:56:59+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "30735d6242bdf32116b9170cc8d5500fb2d56c54",
 "version": "0.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
