#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['markunder']

package_data = \
{'': ['*']}

setup(name='markunder',
      version='0.0.1',
      description='Markup language for chatbots.',
      author='Vyacheslav Rusov',
      author_email='odryfox@gmail.com',
      url='https://github.com/odryfox/markunder',
      packages=packages,
      package_data=package_data,
      python_requires='>=3.6',
     )
