[build-system]
requires = [ "pdm-pep517",]
build-backend = "pdm.pep517.api"

[project]
name = "conflook"
version = "v0.1.0"
description = "Inspect ugly config files."
dependencies = [ "click~=8.0", "tomlkit~=0.7", "pyyaml~=6.0",]
requires-python = ">=3.9"
dynamic = [ "version", "classifiers",]
readme = "README.md"
keywords = [ "cli", "configuration", "inspect", "utility", "development",]
[[project.authors]]
name = "puqeko"

[tool.isort]
profile = "black"
multi_line_output = 3

[project.license]
text = "MIT"

[project.urls]

[project.scripts]
conflook = "conflook:cli"

[tool.pdm.dev-dependencies]
dev = [ "pre-commit~=2.15",]
