VERSION_YEAR = 2021
VERSION_MONTH = int('11')
VERSION_DAY = int('01')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('12')
MAJOR_VERSION = 1
MINOR_VERSION = 2
PATCH_VERSION = 202111011012
version_date = '2021/11/01 10:12'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
