#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['maghsoodtest']

package_data = \
{'': ['*']}

setup(name='maghsoodtest',
      version='0.1.0',
      description='this is simple python package ...',
      author=None,
      author_email='maghsood026 <maghsood95@gmail.com>',
      url=None,
      packages=packages,
      package_data=package_data,
      python_requires='>=3.7',
     )
