name: Python package

on:

  push:
    branches: [ main ]

jobs:

  build:
  
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
        
    environment: prod

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        echo ${{ github.env }}
        python -m pip install --upgrade pip
        python -m pip install flit
    - name: Publish Flit
      env:
          FLIT_USERNAME: ${{ secrets.S_1 }}
          FLIT_PASSWORD: ${{ secrets.S_2 }}
      run: flit publish
  
