
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-28T13:54:08+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "ae29f586bd49f14204dd8507df9d7a74403bffde",
 "version": "0.5.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
