# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trnsysGUI/hydraulicLoops/hydraulicLoopDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_hydraulicLoopDialog(object):
    def setupUi(self, hydraulicLoopDialog):
        hydraulicLoopDialog.setObjectName("hydraulicLoopDialog")
        hydraulicLoopDialog.resize(440, 462)
        self.okCancelButtonBox = QtWidgets.QDialogButtonBox(hydraulicLoopDialog)
        self.okCancelButtonBox.setGeometry(QtCore.QRect(80, 430, 341, 32))
        self.okCancelButtonBox.setOrientation(QtCore.Qt.Horizontal)
        self.okCancelButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.okCancelButtonBox.setObjectName("okCancelButtonBox")
        self.generalGroupBox = QtWidgets.QGroupBox(hydraulicLoopDialog)
        self.generalGroupBox.setGeometry(QtCore.QRect(10, 10, 421, 81))
        self.generalGroupBox.setObjectName("generalGroupBox")
        self.layoutWidget = QtWidgets.QWidget(self.generalGroupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 211, 54))
        self.layoutWidget.setObjectName("layoutWidget")
        self.generalGridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.generalGridLayout.setContentsMargins(0, 0, 0, 0)
        self.generalGridLayout.setObjectName("generalGridLayout")
        self.loopNameLabel = QtWidgets.QLabel(self.layoutWidget)
        self.loopNameLabel.setObjectName("loopNameLabel")
        self.generalGridLayout.addWidget(self.loopNameLabel, 0, 0, 1, 1)
        self.loopName = QtWidgets.QLineEdit(self.layoutWidget)
        self.loopName.setObjectName("loopName")
        self.generalGridLayout.addWidget(self.loopName, 0, 1, 1, 1)
        self.fluidLabel = QtWidgets.QLabel(self.layoutWidget)
        self.fluidLabel.setObjectName("fluidLabel")
        self.generalGridLayout.addWidget(self.fluidLabel, 1, 0, 1, 1)
        self.fluidComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.fluidComboBox.setObjectName("fluidComboBox")
        self.generalGridLayout.addWidget(self.fluidComboBox, 1, 1, 1, 1)
        self.pipesGroupBox = QtWidgets.QGroupBox(hydraulicLoopDialog)
        self.pipesGroupBox.setGeometry(QtCore.QRect(10, 90, 421, 341))
        self.pipesGroupBox.setObjectName("pipesGroupBox")
        self.connectionsTableView = QtWidgets.QTableView(self.pipesGroupBox)
        self.connectionsTableView.setGeometry(QtCore.QRect(10, 20, 401, 311))
        self.connectionsTableView.setObjectName("connectionsTableView")
        self.connectionsTableView.horizontalHeader().setStretchLastSection(True)

        self.retranslateUi(hydraulicLoopDialog)
        self.okCancelButtonBox.accepted.connect(hydraulicLoopDialog.accept)
        self.okCancelButtonBox.rejected.connect(hydraulicLoopDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(hydraulicLoopDialog)

    def retranslateUi(self, hydraulicLoopDialog):
        _translate = QtCore.QCoreApplication.translate
        hydraulicLoopDialog.setWindowTitle(_translate("hydraulicLoopDialog", "Hydraulic loop properties"))
        self.generalGroupBox.setTitle(_translate("hydraulicLoopDialog", "General"))
        self.loopNameLabel.setText(_translate("hydraulicLoopDialog", "Name"))
        self.fluidLabel.setText(_translate("hydraulicLoopDialog", "Fluid"))
        self.pipesGroupBox.setTitle(_translate("hydraulicLoopDialog", "Connections"))
