
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-30T19:13:53-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "6e3f4e89e2cf78221a50f43c202f32b83cee533f",
 "version": "4.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
