
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-01T09:22:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "8cbfe7b1a54cb5c80ec0edcc4469a99d93bbdf6e",
 "version": "2551"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
