
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-26T19:22:04-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "b251f0e8e76742a1f768d2c795553569372ac1c8",
 "version": "0.0.80"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
