[tool.poetry]
name = "PSY-TaLiRo"
version = "1.0.0b2"
description = "System-level verification library using STL"
authors = ["Quinn Thibeault <qthibeau@asu.edu>", "Jacob Anderson <andersonjwan@asu.edu>"]
license = "BSD-3-Clause"
packages = [
    {include = "staliro", from = "src"}
]

[tool.poetry.dependencies]
python = ">=3.7.1, <3.10"
antlr4-python3-runtime = "~=4.5.3"
attrs = "^21.0.0"
numpy = "^1.20.2"
scipy = "^1.6.2"
typing-extensions = "^3.10.0"

[tool.poetry.dev-dependencies]
mypy = "^0"
flake8 = "^3.9.0"
flake8-comprehensions = "^3.4.0"
flake8-pyi = "^20.10.0"
flake8-return = "^1.1.2"
pep8-naming = "^0.11.1"
flake8-use-fstring = "^1.1"
flake8-import-order = "^0.18.1"
flake8-annotations-complexity = "^0.0.6"
flake8-todo = "^0.7"
black = "^21.5b1"
isort = "^5.9.2"
Sphinx = "^4.1.2"
sphinx-autodocgen = "^1.2"
pandas = "^1.3.1"
rtamt = {git = "https://github.com/nickovic/rtamt.git"}
tltk-mtl = "^0.0.27"
sphinx-autobuild = "^2021.3.14"
furo = "^2021.8.11-beta.42"
rstcheck = "^3.3.1"
plotly = "^5.3.1"
aerobench = {git = "https://github.com/qthibeault/aerobenchvvpython.git"}
kaleido = "0.2.1"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
