#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['crabnet', 'crabnet.utils']

package_data = \
{'': ['*']}

install_requires = \
['python',
 'numpy',
 'pandas',
 'scipy',
 'scikit_learn',
 'matplotlib',
 'seaborn',
 'pytorch>=1.7',
 'cudatoolkit==11.3.*',
 'tqdm',
 'joblib',
 'psutil']

setup(name='crabnet',
      version='1.0.1',
      description='Predict materials properties using only the composition information.',
      author=None,
      author_email='"Sterling G. Baird" <sterling.baird@utah.edu>',
      url=None,
      packages=packages,
      package_data=package_data,
      install_requires=install_requires,
     )
