- hosts: kube_control_plane
  gather_facts: true
  tasks:
    - name: Copy Kubernetes manifests
      copy:
        src: "{{ kubernetes_sample_dir }}"
        dest: "{{ ansible_env.HOME }}"
        remote_src: false

    - name: Apply Kubernetes manifests
      command: "kubectl apply -f {{ ansible_env.HOME }}/kubernetes_sample"
