- hosts: kube_control_plane
  gather_facts: true
  tasks:
    - name: Create Kubernetes config directory
      file: 
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory

    - name: Copy Kubernetes config file
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "{{ ansible_env.HOME }}/.kube/config"
        remote_src: true
      become: true

    - name: Change Kubernetes config file permission
      file:
        path: "{{ ansible_env.HOME }}/.kube/config"
        owner: "{{ ansible_effective_user_id }}"
        group: "{{ ansible_effective_group_id }}"
      become: true
    
    - name: Set Kubernetes config path as an environment variable
      lineinfile:
        dest: /root/.bashrc
        line: "export KUBECONFIG=/etc/kubernetes/admin.conf"
      become: true
      ignore_errors: yes
