
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "225ef793e0e371557640e0d2a6de380bb9f4a557",
 "version": "1.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
