# coding: utf-8

"""
    streamduo.com API

    Swagger docs for streamduo.com  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: steve@streamduo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.stream_record_controller_api import StreamRecordControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestStreamRecordControllerApi(unittest.TestCase):
    """StreamRecordControllerApi unit test stubs"""

    def setUp(self):
        self.api = StreamRecordControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_last_n_records_using_get(self):
        """Test case for get_last_n_records_using_get

        getLastNRecords  # noqa: E501
        """
        pass

    def test_get_record_using_get(self):
        """Test case for get_record_using_get

        getRecord  # noqa: E501
        """
        pass

    def test_get_unread_records_using_get(self):
        """Test case for get_unread_records_using_get

        getUnreadRecords  # noqa: E501
        """
        pass

    def test_write_record_using_post(self):
        """Test case for write_record_using_post

        writeRecord  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
