# coding: utf-8

"""
    streamduo.com API

    Swagger docs for streamduo.com  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: steve@streamduo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.stream_affiliation_record import StreamAffiliationRecord  # noqa: E501
from swagger_client.rest import ApiException


class TestStreamAffiliationRecord(unittest.TestCase):
    """StreamAffiliationRecord unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreamAffiliationRecord(self):
        """Test StreamAffiliationRecord"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.stream_affiliation_record.StreamAffiliationRecord()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
