# coding: utf-8

"""
    streamduo.com API

    Swagger docs for streamduo.com  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: steve@streamduo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.read_record_request import ReadRecordRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestReadRecordRequest(unittest.TestCase):
    """ReadRecordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReadRecordRequest(self):
        """Test ReadRecordRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.read_record_request.ReadRecordRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
