
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-29T22:04:40+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc6205de703e597a50f13bdeab7d693a9c8859c0",
 "version": "2550"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
