
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-27T14:54:01+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "a03fabc5ab7a3694535b502bbcefbb384ec651e2",
 "version": "4.8"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
