[tool.poetry]
name = "bunches"
version = "0.1.0"
description = "flexible, extensible python data structures"
authors = ["Corey Rayburn Yung <coreyrayburnyung@gmail.com>"]
license = "Apache"
readme = "README.md"
homepage = "https://github.com/WithPrecedent/bunches"
repository = "https://github.com/WithPrecedent/bunches"

[tool.poetry.dependencies]
python = "^3.9"
more-itertools = "^8.10.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
