name: uncompyle6 (windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        os: [windows]
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Until the next xdis release
        pip install git+git://github.com/rocky/python-xdis.git#egg=xdis
        pip install -e .
        pip install -r requirements-dev.txt
    - name: Test uncompyle6
      run: |
        make check
