
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-31T02:19:51+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "31324be8f1d93faf6daa91cbaf4511a3968af097",
 "version": "0.3.dev2144"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
