
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-28T21:59:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9a9dd99eb65472c2d76a5356b47edc987005fb1b",
 "version": "0.9.18"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
