# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/01_constants.ipynb (unless otherwise specified).

__all__ = ["TOKEN_FILE", "CREDENTIALS_FILE", "PROJECT", "DATASET", "SCOPES"]

# Cell
TOKEN_FILE = "./credentials/token.json"
CREDENTIALS_FILE = "./credentials/credentials.json"
PROJECT = "p-e-omni-marketingcloud-p"
DATASET = "discovery_tmp"
SCOPES = ["https://www.googleapis.com/auth/bigquery"]
