
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-02T13:07:27-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "53f772054fc7077736e02a5b509f5ef7bc1caa94",
 "version": "0.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
