
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-31T07:50:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ededd505be03eb82b50d312bebb7cf95b79e8b3b",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
