
# This file was generated by 'versioneer.py' (0.15+dev) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d60c5a631aedf2328e4492125d9b86f595e43d00",
 "version": "1.7.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
