'''__init__.py'''


from mastapy._internal.dummy_base_class_importer import _DummyBaseClassImport


with _DummyBaseClassImport():
    from ._938 import AddendumModificationDistributionRule
    from ._939 import BacklashSpecification
    from ._940 import BasicRackProfiles
    from ._941 import CaseHardeningProperties
    from ._942 import CreateNewSuitableCutterOption
    from ._943 import CrossedAxisCylindricalGearPair
    from ._944 import CrossedAxisCylindricalGearPairLineContact
    from ._945 import CrossedAxisCylindricalGearPairPointContact
    from ._946 import CylindricalGearAbstractRack
    from ._947 import CylindricalGearAbstractRackFlank
    from ._948 import CylindricalGearBasicRack
    from ._949 import CylindricalGearBasicRackFlank
    from ._950 import CylindricalGearCuttingOptions
    from ._951 import CylindricalGearDefaults
    from ._952 import CylindricalGearDesign
    from ._953 import CylindricalGearDesignConstraint
    from ._954 import CylindricalGearDesignConstraints
    from ._955 import CylindricalGearDesignConstraintsDatabase
    from ._956 import CylindricalGearDesignConstraintSettings
    from ._957 import CylindricalGearDesignSettings
    from ._958 import CylindricalGearFlankDesign
    from ._959 import CylindricalGearMeshDesign
    from ._960 import CylindricalGearMeshFlankDesign
    from ._961 import CylindricalGearMicroGeometrySettings
    from ._962 import CylindricalGearPinionTypeCutter
    from ._963 import CylindricalGearPinionTypeCutterFlank
    from ._964 import CylindricalGearProfileMeasurement
    from ._965 import CylindricalGearProfileMeasurementType
    from ._966 import CylindricalGearProfileModifications
    from ._967 import CylindricalGearSetDesign
    from ._968 import CylindricalGearSetFlankDesign
    from ._969 import CylindricalGearSetMacroGeometryOptimiser
    from ._970 import CylindricalGearSetManufacturingConfigurationSelection
    from ._971 import CylindricalGearTableMGItemDetail
    from ._972 import CylindricalGearTableWithMGCharts
    from ._973 import CylindricalGearToothThicknessSpecification
    from ._974 import CylindricalMeshAngularBacklash
    from ._975 import CylindricalMeshedGear
    from ._976 import CylindricalMeshedGearFlank
    from ._977 import CylindricalMeshLinearBacklashSpecification
    from ._978 import CylindricalPlanetaryGearSetDesign
    from ._979 import CylindricalPlanetGearDesign
    from ._980 import DIN3967AllowanceSeries
    from ._981 import DIN3967ToleranceSeries
    from ._982 import DoubleAxisScaleAndRange
    from ._983 import FinishStockSpecification
    from ._984 import FinishToothThicknessDesignSpecification
    from ._985 import GearFitSystems
    from ._986 import GearManufacturingConfigSetupViewModel
    from ._987 import GearSetFCAImportSetup
    from ._988 import GearSetManufacturingConfigurationSetup
    from ._989 import GeometrySpecificationType
    from ._990 import HardenedMaterialProperties
    from ._991 import HardnessProfileCalculationMethod
    from ._992 import HeatTreatmentType
    from ._993 import ISO6336Geometry
    from ._994 import ISO6336GeometryBase
    from ._995 import ISO6336GeometryForShapedGears
    from ._996 import ISO6336GeometryManufactured
    from ._997 import LinearBacklashSepcification
    from ._998 import LTCALoadCaseModifiableSettings
    from ._999 import LtcaSettings
    from ._1000 import MicroGeometryConvention
    from ._1001 import MicroGeometryProfileConvention
    from ._1002 import Micropitting
    from ._1003 import NamedPlanetAssemblyIndex
    from ._1004 import NamedPlanetSideBandAmplitudeFactor
    from ._1005 import ReadonlyToothThicknessSpecification
    from ._1006 import RelativeMeasurementViewModel
    from ._1007 import RelativeValuesSpecification
    from ._1008 import Scuffing
    from ._1009 import ScuffingCoefficientOfFrictionMethods
    from ._1010 import ScuffingTemperatureMethodsAGMA
    from ._1011 import ScuffingTemperatureMethodsISO
    from ._1012 import ShaperEdgeTypes
    from ._1013 import SpurGearLoadSharingCodes
    from ._1014 import StandardRack
    from ._1015 import StandardRackFlank
    from ._1016 import SurfaceRoughness
    from ._1017 import ThicknessType
    from ._1018 import TiffAnalysisSettings
    from ._1019 import TipAlterationCoefficientMethod
    from ._1020 import TolerancedMetalMeasurements
    from ._1021 import TolerancedValueSpecification
    from ._1022 import ToothFlankFractureAnalysisSettings
    from ._1023 import ToothThicknessSpecification
    from ._1024 import ToothThicknessSpecificationBase
    from ._1025 import TypeOfMechanismHousing
    from ._1026 import Usage
