
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-27T11:15:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c0d6cfb1bdf526fd9ddd32899fefca250a3aa7a0",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
