# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import proxy_pb2 as proto_dot_proxy__pb2


class ProxyApiStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetProxies = channel.unary_unary(
            '/proxy.ProxyApi/GetProxies',
            request_serializer=proto_dot_proxy__pb2.ProxyRequest.SerializeToString,
            response_deserializer=proto_dot_proxy__pb2.ProxyReply.FromString,
        )


class ProxyApiServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetProxies(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProxyApiServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'GetProxies': grpc.unary_unary_rpc_method_handler(
            servicer.GetProxies,
            request_deserializer=proto_dot_proxy__pb2.ProxyRequest.FromString,
            response_serializer=proto_dot_proxy__pb2.ProxyReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'proxy.ProxyApi', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ProxyApi(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetProxies(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proxy.ProxyApi/GetProxies',
                                             proto_dot_proxy__pb2.ProxyRequest.SerializeToString,
                                             proto_dot_proxy__pb2.ProxyReply.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
