[tool.poetry]
name = "manga-scrap"
version = "0.3.0"
description = "A flexible and extensible library to scrap manga and convert it to usable models"
authors = ["Andrés Riquelme <andresfranco.rs@gmail.com>", "Sebastián Sandoval <root.kan.ss@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
requests = "^2.26.0"
beautifulsoup4 = "^4.9.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
