[tool.poetry]
name = "mmoreira_csv_converter"
version = "0.1.7"
description = "Convert csv to json or convert json to csv. Publishing only for learning purpose at PUC-MG. DS Class"
authors = ["Marcelo Moreira G Silva <mqestatistico@gamil.com>"]
readme = "readme.md"

[tool.poetry.dependencies]
python = "^3.9"
click = "^8.0.3"
flake8 = "^4.0.1"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
click = "^8.0.3"
mypy = "^0.910"
pytest = "^6.2.5"
black = "^21.9b0"
isort = "^5.9.3"
ipython = "^7.28.0"
pathlib = "^1.0.1"
autopep8 = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
csv2json = 'mmoreira_csv_converter.csv2json:converter'

[tool.black]
line-length = 99

[tool.isort]
profile = "black"