[tool.poetry]
name = "lb-classes"
version = "0.1.0"
description = "Implements classes for stocks model and db client"
authors = ["Lionel Barbagallo"]
packages = [{include = "classes"}]

[tool.poetry.dependencies]
python = "^3.7.10"
SQLAlchemy = "^1.4.26"
psycopg2-binary = "^2.9.1"
postgres = "^4.0"

[tool.poetry.dev-dependencies]
pylint = "^2.11.1"
black = "^21.9b0"
isort = "^5.9.3"
mypy = "^0.910"
flake8-docstrings = "^1.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
