
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-02T11:22:09+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f049f91892aefe8e57ce3557a0aef2b44606c77b",
 "version": "0.7.1.post.dev138"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
