
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-01T17:19:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb347fe1fcb8a8632d98f99d47dd8483adcc2025",
 "version": "2021.10.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
