
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-03T16:46:16+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "c48a75fea41ff5e77330255bbeccebb3a11c2a7d",
 "version": "1.0.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
