# coding: utf-8

"""
    streamduo.com API

    Swagger docs for streamduo.com  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: steve@streamduo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_controller_api import UserControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserControllerApi(unittest.TestCase):
    """UserControllerApi unit test stubs"""

    def setUp(self):
        self.api = UserControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_user_using_post(self):
        """Test case for create_user_using_post

        createUser  # noqa: E501
        """
        pass

    def test_get_user_using_get(self):
        """Test case for get_user_using_get

        getUser  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
