# coding: utf-8

"""
    streamduo.com API

    Swagger docs for streamduo.com  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: steve@streamduo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.stream_update_client_id_request import StreamUpdateClientIDRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestStreamUpdateClientIDRequest(unittest.TestCase):
    """StreamUpdateClientIDRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStreamUpdateClientIDRequest(self):
        """Test StreamUpdateClientIDRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.stream_update_client_id_request.StreamUpdateClientIDRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
