# coding: utf-8

"""
    streamduo.com API

    Swagger docs for streamduo.com  # noqa: E501

    OpenAPI spec version: 1.0
    Contact: steve@streamduo.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.client_controller_api import ClientControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestClientControllerApi(unittest.TestCase):
    """ClientControllerApi unit test stubs"""

    def setUp(self):
        self.api = ClientControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_client_using_delete(self):
        """Test case for delete_client_using_delete

        deleteClient  # noqa: E501
        """
        pass

    def test_get_client_details_using_get(self):
        """Test case for get_client_details_using_get

        getClientDetails  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
