name: PyPi release

# Controls when the workflow will run
on:
  push:
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # see: https://github.community/t/how-to-get-just-the-tag-name/16241/7
      - name: Get the version
        id: get_version
        shell: bash
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Set global variables
        shell: bash
        run: |
          echo "PACKAGE_NAME=tkinter-tooltip" >> $GITHUB_ENV
          echo "VERSION=${{ steps.get_version.outputs.VERSION}}" >> $GITHUB_ENV

      - name: Build Python wheels
        shell: bash
        run: |
          echo "Branch:" $GITHUB_REF
          echo "git SHA:" $GITHUB_SHA
          echo "Version:" ${VERSION}
          sed -i "s/PLACEHOLDER/${VERSION}/g" "tktooltip/_version.py"

          sudo apt install python3-pip
          pip3 install --upgrade pip setuptools wheel tkinter
          python3 setup.py sdist bdist_wheel

      # Save dist/ directory to persist for the next job "publish"
      - uses: actions/upload-artifact@v2
        with:
          name: python-wheels
          path: dist

  publish:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: python-wheels
          path: dist

      # Upload to PyPi and TestPyPi only when we create tags
      - name: Publish to TestPyPi
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_KEY }}
          repository_url: https://test.pypi.org/legacy/
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_KEY }}
