# Generated by Django 3.2 on 2021-10-27 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest_admin', '0003_auto_20211027_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='routeexec',
            name='inspected_from_db',
            field=models.IntegerField(blank=True, help_text='是否需要将库中表导入为django的model。1，0. eg: 0 ', null=True),
        ),
        migrations.AddField(
            model_name='routeexec',
            name='table_name',
            field=models.TextField(blank=True, help_text='the table name. eg: danwei. ONLY needed if inspected_from_db=1', null=True),
        ),
    ]
