# coding: utf-8

"""
    Modern Logic Api

    Manage and version your customer decision logic outside of your codebase  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: info@usemodernlogic.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import modern_logic_client
from modern_logic_client.models.webhook import Webhook  # noqa: E501
from modern_logic_client.rest import ApiException


class TestWebhook(unittest.TestCase):
    """Webhook unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebhook(self):
        """Test Webhook"""
        # FIXME: construct object with mandatory attributes with example values
        # model = modern_logic_client.models.webhook.Webhook()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
