
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-28T14:06:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7504888b0d6817862feb21b8ef0d0539d2bd9d2",
 "version": "2021.10.28"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
