
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-10-31T02:15:19+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fe4d6f9c0bf934575610eec22e3e569a6dcb0968",
 "version": "0.8.dev2144"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
