
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2021-11-01T11:30:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "1edb11cc21a9ebe6a7c9caaa18f10a9f195eabc2",
 "version": "0.7.1.post.dev128"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
