[tool.poetry]
name = "brewblox-dev"
version = "1.9.1"
description = "Brewblox development tools"
authors = ["BrewPi <development@brewpi.com>"]
license = "GPL-3.0"

[tool.poetry.dependencies]
python = ">=3.6,<4"
python-dotenv = "^0.19.0"
click = "^8.0.1"

[tool.poetry.dev-dependencies]
pytest-flake8 = "^1.0.7"
pytest-cov = "^2.12.1"
pytest-mock = "^3.6.1"
flake8 = "^3.9.2"
autopep8 = "^1.5.7"

[tool.poetry.scripts]
brewblox-dev = 'brewblox_dev.__main__:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
