{% set name = "mat_discover" %}
{% set version = "1.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mat_discover-{{ version }}.tar.gz
  sha256: d54943905341f3f67d0b97e6e0a58ba2b34f04d6746425de9114a246d794fc32
  # git_url: https://github.com/sparks-baird/mat_discover.git
  # git_rev: {{ version }}
  # git_depth: 1 # (Defaults to -1/not shallow)

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m  pip install . -vv

requirements:
  host:
    - pip
    - flit
    - python >=3.7
  run:
    - python >=3.7
    - matplotlib >=3.4.3
    - pandas
    - pytorch
    - plotly
    - scipy
    - cudatoolkit ==11.3.1
    - numba >=0.53.1
    - seaborn
    - tqdm
    - python-kaleido
    - umap-learn
    - psutil
    - numpy
    - scikit-learn
    - cython
    - hdbscan
    - pymatgen
    - dill
    - pqdm ==0.1.0 #sgbaird
    # - elmd ==0.4.8 #sgbaird
    - crabnet
    - chem_wasserstein

test:
  imports:
    - mat_discover
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/mat_discover/
  summary: Data-driven materials discovery based on composition.
  dev_url: https://github.com/sparks-baird/mat_discover
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sgbaird
