[tool.poetry]
name = "rosys"
version = "v0.3.1"
description = "Modular Robot System With Elegant Automation Capabilities"
authors = ["Zauberzeug GmbH <info@zauberzeug.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/zauberzeug/rosys"
keywords = ["robot", "framework", "automation", "control", "steer"]

[tool.poetry.dependencies]
python = "^3.9 <3.10"
requests = "^2.25.1"
simplejson = "^3.17.2"
pyserial = "^3.5"
numpy = "^1.20.1"
retry = "^0.9.2"
aioserial = "^1.3.0"
simplejpeg = "^1.5.0"
aiohttp = "^3.7.4"
opencv-contrib-python-headless = "^4.5.2"
pycurl = "^7.43.0"
pydantic = "^1.8.2"
asyncio = "^3.4.3"
Pillow = "^8.3.0"
nicegui = "0.5.9"
python-socketio = {extras = ["asyncio_client"], version = "^5.3.0"}
svgpathtools = "^1.4.1"
networkx = "^2.6.2"
scipy = "^1.7.1"
bacs = "0.1.3"
Shapely = "^1.7.1"
more-itertools = "^8.10.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.1"
pytest-watch = "^4.2.0"
pytest-flakefinder = "^1.0.0"
pytest-profiling = "^1.7.0"
autopep8 = "^1.5.5"
debugpy = "^1.2.1"
line-profiler = "3.1.0"
icecream = "^2.1.0"
pytest-asyncio = "^0.15.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
