[tool.poetry]
name = "ergen"
version = "0.1.0"
description = ""
authors = ["Naoya Yamashita <conao3@gmail.com>"]
license = "Apache-2.0"

[tool.poetry.scripts]
ergen = "ergen.cli:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = "^0.4.0"
Jinja2 = "^3.0.2"
pydantic = "^1.8.2"
PyYAML = "^6.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
