[tool.poetry]
name = "Marsworks"
version = "0.7.0"
description = "An API Wrapper around NASA's Mars Rover Photos API written in Python; providing sync and async support."
authors = ["mooncell07 <mooncell07@users.noreply.github.com>"]
license = "MIT"
homepage = "https://github.com/mooncell07/Marsworks"
readme = "PYPI-README.md"
keywords = ["Mars Photos", "Api-Wrapper", "Async", "NASA"]
documentation = "https://mooncell07.github.io/Marsworks/"


[tool.poetry.dependencies]
python = "^3.7"
httpx = "^0.18.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^3.9.2"
pre-commit = "^2.13.0"
mypy = "^0.910"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
